// @generated by scripts/generate-note-math.mjs. Do not edit manually.

pub const NOTE_NAMES: [&str; 12] = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
];

pub fn canonical_note_name(name: &str) -> Option<&'static str> {
    NOTE_NAMES
        .iter()
        .copied()
        .find(|candidate| *candidate == name)
}

pub fn note_name_index(name: &str) -> Option<usize> {
    NOTE_NAMES.iter().position(|candidate| *candidate == name)
}

pub fn note_name_from_midi(midi: i32) -> &'static str {
    NOTE_NAMES[midi.rem_euclid(NOTE_NAMES.len() as i32) as usize]
}

pub fn octave_from_midi(midi: i32) -> i32 {
    midi.div_euclid(NOTE_NAMES.len() as i32) - 1
}

pub fn note_to_midi(name: &str, octave: i32) -> i32 {
    (octave + 1) * NOTE_NAMES.len() as i32 + note_name_index(name).unwrap_or(0) as i32
}

pub fn midi_to_frequency(midi: f32, a4: f32) -> f32 {
    if !midi.is_finite() || !a4.is_finite() || a4 <= 0.0 {
        return 0.0;
    }
    a4 * 2.0_f32.powf((midi - 69.0_f32) / 12.0_f32)
}

pub fn frequency_to_midi(frequency: f32, a4: f32) -> f32 {
    if !frequency.is_finite() || frequency <= 0.0 || !a4.is_finite() || a4 <= 0.0 {
        return 0.0;
    }
    69.0_f32 + (12.0_f32 * (frequency / a4).log2())
}

pub fn frequency_to_nearest_midi(frequency: f32, a4: f32) -> i32 {
    frequency_to_midi(frequency, a4).round() as i32
}

pub fn get_cents(frequency: f32, target_frequency: f32) -> f32 {
    if !frequency.is_finite()
        || frequency <= 0.0
        || !target_frequency.is_finite()
        || target_frequency <= 0.0
    {
        return 0.0;
    }
    1200.0_f32 * (frequency / target_frequency).log2()
}

pub fn apply_cents_offset_frequency(frequency: f32, cents: f32) -> f32 {
    if !frequency.is_finite() || frequency <= 0.0 || !cents.is_finite() {
        return frequency;
    }
    frequency * 2.0_f32.powf(cents / 1200.0_f32)
}

pub fn format_note_display(name: &str, octave: i32) -> String {
    format!("{name}{octave}")
}

pub fn format_freq(frequency: f32) -> String {
    format!("{frequency:.1}")
}

pub fn closest_frequency_index<I>(
    frequency: f32,
    target_frequencies: I,
    scale: f32,
) -> Option<usize>
where
    I: IntoIterator<Item = f32>,
{
    if !frequency.is_finite() || frequency <= 0.0 || !scale.is_finite() || scale <= 0.0 {
        return None;
    }
    target_frequencies
        .into_iter()
        .enumerate()
        .filter(|(_, target_frequency)| target_frequency.is_finite() && *target_frequency > 0.0)
        .min_by(|(_, left), (_, right)| {
            let target_frequency = *left;
            let left_distance = (frequency / (target_frequency * scale)).log2().abs();
            let target_frequency = *right;
            let right_distance = (frequency / (target_frequency * scale)).log2().abs();
            left_distance.total_cmp(&right_distance)
        })
        .map(|(index, _)| index)
}
