import type { CentsHistoryPoint } from '../../domain/centsHistory';
import type { DetectionFrame, SpectrumFrame, WaveformFrame } from '../../types/frames';
import type { Note } from '../../utils/notes';
import type { DisplayMode, LayoutMode, ThemeMode } from '../../utils/settingsStorage';
import type { SessionStatus } from '../../session/sessionLifecycle';

export interface AnalysisPort {
  activate(): void;
  readonly centsHistory: CentsHistoryPoint[];
  clearError(): void;
  deactivate(): void;
  readonly detectionFrame: DetectionFrame;
  readonly displayMode: DisplayMode;
  readonly error: string | null;
  readonly feedbackFlash: boolean;
  readonly feedbackSound: boolean;
  readonly feedbackVibrate: boolean;
  formatFreq(frequency: number): string;
  readonly isListening: boolean;
  readonly layoutMode: LayoutMode;
  readonly leftHanded: boolean;
  readonly readoutStability: number;
  readonly sessionStatus: SessionStatus;
  setDisplayMode(value: unknown): void;
  setFeedbackFlash(value: boolean): void;
  setFeedbackSound(value: boolean): void;
  setFeedbackVibrate(value: boolean): void;
  setLayoutMode(value: unknown): void;
  setLeftHanded(value: boolean): void;
  setReadoutStability(value: number): void;
  setShowSpectrogram(value: boolean): void;
  setShowSpectrum(value: boolean): void;
  setShowWaveform(value: boolean): void;
  setThemeMode(value: unknown): void;
  readonly showSpectrogram: boolean;
  readonly showSpectrum: boolean;
  readonly showWaveform: boolean;
  readonly smoothedFrequency: number | null;
  readonly spectrumFrame: SpectrumFrame | null;
  start(): Promise<void>;
  stop(): Promise<void>;
  readonly targetNote: Note;
  readonly themeMode: ThemeMode;
  toggleFullscreen(): Promise<void>;
  toggle(): Promise<void>;
  readonly usingNativeAudio: boolean;
  readonly waveformFrame: WaveformFrame | null;
}
