import type { AudioFrameTimebase, ExactPcmCapture } from '../../ports/audioInput';
import type { DetectorBackend } from '../../types/detectorBackend';
import type { DetectionFrame } from '../../types/frames';
import type { Note, Tuning } from '../../utils/notes';
import type { AudioBackend, DisplayMode } from '../../utils/settingsStorage';
import type { SessionStatus } from '../../session/sessionLifecycle';

export interface LiveTunerPort {
  readonly a4: number;
  readonly allTunings: Tuning[];
  readonly audioBackend: AudioBackend;
  beginExactPcmCapture(): boolean;
  readonly cents: number;
  clearError(): void;
  readonly currentNoteDisplay: string | null;
  readonly currentTuning: Tuning;
  readonly detectionFrame: DetectionFrame;
  readonly detectionFrameTimebase: AudioFrameTimebase | null;
  readonly detectorBackend: DetectorBackend;
  readonly diagnosticFrame: DetectionFrame;
  readonly displayMode: DisplayMode;
  readonly error: string | null;
  readonly exactPcmCaptureAvailable: boolean;
  readonly feedbackFlash: boolean;
  readonly feedbackSound: boolean;
  readonly feedbackVibrate: boolean;
  readonly fileAudioDuration: number;
  readonly fileAudioName: string | null;
  readonly fileAudioProgress: number;
  finishExactPcmCapture(): ExactPcmCapture | null;
  formatFreq(frequency: number): string;
  getNoteDisplay(note: Pick<Note, 'name' | 'octave'>): string;
  readonly hasDetection: boolean;
  readonly inputDevices: MediaDeviceInfo[];
  readonly isInTune: boolean;
  readonly isListening: boolean;
  readonly leftHanded: boolean;
  loadAudioFile(file: File): Promise<boolean>;
  readonly nativeAudioAvailable: boolean;
  readonly readoutStability: number;
  readonly referencePlaying: boolean;
  refreshInputDevices(): Promise<void>;
  readonly selectedInputDeviceId: string;
  readonly selectedString: Note | null;
  readonly selectedStringIndex: number | null;
  readonly sessionStatus: SessionStatus;
  setA4(value: number): void;
  setAudioBackend(backend: AudioBackend): Promise<void>;
  setDisplayMode(value: unknown): void;
  setInputDevice(deviceId: string): Promise<void>;
  setTuning(tuning: Tuning): void;
  start(): Promise<void>;
  stop(): Promise<void>;
  readonly strings: Note[];
  readonly targetNote: Note;
  toggleReferenceTone(): Promise<void>;
  toggle(): Promise<void>;
  toggleString(note: Note, index?: number): void;
  useMicrophoneInput(): Promise<void>;
  readonly usingFileAudio: boolean;
  readonly usingNativeAudio: boolean;
  readonly usingSyntheticAudio: boolean;
  readonly volume: number;
}
