import type { AudioFrameTimebase, ExactPcmCapture } from '../../ports/audioInput';
import type { DetectorBackend } from '../../types/detectorBackend';
import type { DetectionFrame } from '../../types/frames';
import type { Note, Tuning } from '../../utils/notes';
import type { AudioBackend, DisplayMode } from '../../utils/settingsStorage';
import type { SessionStatus } from '../../session/sessionLifecycle';

export interface LiveTunerPort {
  a4: number;
  allTunings: Tuning[];
  audioBackend: AudioBackend;
  beginExactPcmCapture(): boolean;
  cents: number;
  clearError(): void;
  currentNoteDisplay: string | null;
  currentTuning: Tuning;
  detectionFrame: DetectionFrame;
  detectionFrameTimebase: AudioFrameTimebase | null;
  detectorBackend: DetectorBackend;
  diagnosticFrame: DetectionFrame;
  displayMode: DisplayMode;
  error: string | null;
  exactPcmCaptureAvailable: boolean;
  fileAudioDuration: number;
  fileAudioName: string | null;
  fileAudioProgress: number;
  finishExactPcmCapture(): ExactPcmCapture | null;
  formatFreq(frequency: number): string;
  getNoteDisplay(note: Pick<Note, 'name' | 'octave'>): string;
  hasDetection: boolean;
  inputDevices: MediaDeviceInfo[];
  isInTune: boolean;
  isListening: boolean;
  leftHanded: boolean;
  loadAudioFile(file: File): Promise<boolean>;
  nativeAudioAvailable: boolean;
  referencePlaying: boolean;
  refreshInputDevices(): Promise<void>;
  selectedInputDeviceId: string;
  selectedString: Note | null;
  selectedStringIndex: number | null;
  sessionStatus: SessionStatus;
  setA4(value: number): void;
  setAudioBackend(backend: AudioBackend): Promise<void>;
  setDisplayMode(value: unknown): void;
  setInputDevice(deviceId: string): Promise<void>;
  setTuning(tuning: Tuning): void;
  start(): Promise<void>;
  stop(): Promise<void>;
  strings: Note[];
  targetNote: Note;
  toggleReferenceTone(): Promise<void>;
  toggleString(note: Note, index?: number): void;
  useMicrophoneInput(): Promise<void>;
  usingFileAudio: boolean;
  usingNativeAudio: boolean;
  usingSyntheticAudio: boolean;
  volume: number;
}
