use serde::Deserialize;
use std::{
    collections::BTreeSet,
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct MusicRegistry {
    schema_version: u32,
    note_names: Vec<String>,
    instruments: Vec<Instrument>,
    tunings: Vec<Tuning>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Instrument {
    id: String,
    default_tuning_id: String,
}

#[derive(Deserialize)]
struct Tuning {
    id: String,
    name: String,
    instrument: String,
    strings: Vec<(String, i32)>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let registry_path = manifest_dir.join("../registry/music-registry.json");
    println!("cargo:rerun-if-changed={}", registry_path.display());

    let registry = load_registry(&registry_path);
    validate_registry(&registry);
    let generated = generate_rust(&registry);
    let output =
        PathBuf::from(env::var("OUT_DIR").expect("build output")).join("music_registry.rs");
    fs::write(output, generated).expect("write generated music registry");
}

fn load_registry(path: &Path) -> MusicRegistry {
    let source = fs::read_to_string(path).expect("read shared music registry");
    serde_json::from_str(&source).expect("parse shared music registry")
}

fn validate_registry(registry: &MusicRegistry) {
    assert_eq!(
        registry.schema_version, 1,
        "unsupported music registry schema"
    );
    assert_eq!(
        registry.note_names.len(),
        12,
        "registry must define 12 notes"
    );

    let note_names = unique_ids(registry.note_names.iter(), "note");
    let instrument_ids = unique_ids(
        registry.instruments.iter().map(|instrument| &instrument.id),
        "instrument",
    );
    let tuning_ids = unique_ids(registry.tunings.iter().map(|tuning| &tuning.id), "tuning");

    for instrument in &registry.instruments {
        assert!(
            instrument.default_tuning_id == "chromatic"
                || tuning_ids.contains(instrument.default_tuning_id.as_str()),
            "instrument {} references missing tuning {}",
            instrument.id,
            instrument.default_tuning_id,
        );
    }

    for tuning in &registry.tunings {
        assert!(
            instrument_ids.contains(tuning.instrument.as_str()),
            "tuning {} references missing instrument {}",
            tuning.id,
            tuning.instrument,
        );
        for (name, _) in &tuning.strings {
            assert!(note_names.contains(name.as_str()), "invalid note {name}");
        }
    }

    let standard = registry
        .tunings
        .iter()
        .find(|tuning| tuning.id == "standard")
        .expect("standard tuning");
    assert_eq!(
        standard.strings.len(),
        6,
        "standard guitar must have six strings"
    );
}

fn unique_ids<'a>(ids: impl Iterator<Item = &'a String>, kind: &str) -> BTreeSet<&'a str> {
    let mut unique = BTreeSet::new();
    for id in ids {
        assert!(unique.insert(id.as_str()), "duplicate {kind} id {id}");
    }
    unique
}

fn generate_rust(registry: &MusicRegistry) -> String {
    let mut source =
        String::from("// @generated by pitch-core/build.rs from registry/music-registry.json.\n\n");

    source.push_str("pub fn get_tunings() -> Vec<Tuning> {\n    vec![\n");
    for tuning in &registry.tunings {
        writeln!(
            source,
            "        Tuning {{ name: {:?}, strings: equal_tempered_notes(&[",
            tuning.name,
        )
        .unwrap();
        for (name, octave) in &tuning.strings {
            writeln!(source, "            ({name:?}, {octave}),").unwrap();
        }
        source.push_str("        ]) },\n");
    }
    source.push_str("    ]\n}\n");
    source
}
